### PR TITLE
Rewrite with cleaner API and no patching into MARC classes

### PR DESCRIPTION
**Pull request by jpstroop**
@terrellt or @flyingzumwalt Let me know what you think.

When this is OK, I can proceed with pulibrary/plum#1.

### CODE REVIEW

**Comment by terrellt** [comment]
@jpstroop It seems like the old version had more information from pulfa (IE https://github.com/pulibrary/pul_metadata_services/blob/71d537910bb62b0e91993362095bdd60b6d84e93/lib/pul_metadata_services/external_metadata_source.rb#L370). Do you want to do that work here, or just open another ticket?

**Comment by terrellt** [comment]
I'd also like to see a #attributes method which we can use for plum. (so that we can do https://github.com/pulibrary/plum/blob/master/app/models/scanned_book.rb#L28)

**Comment by jpstroop** [comment]
I was just sitting down to add more to the EAD extraction piece. With this PR I'm primarily concerned about how the code is organized. I'll open another issue. 

I see what you're doing w/ `#attributes`. Just an instance method on the `*Record` classes is what you have in mind, right?

**Comment by terrellt** [comment]
@jpstroop Yup, that's what I have in mind. We can make it another ticket if you'd prefer.

**Comment by jpstroop** [comment]
#5 and #6

**Comment by terrellt** [comment]
:+1:

**Pull request merged**
