### PR TITLE
Implement #attributes

### LINKED ISSUE #6: Add #attributes instance method to *Record classes
Like [this](https://github.com/pulibrary/plum/blob/master/app/models/remote_bibdata.rb#L14-L21) so that something like [this](https://github.com/pulibrary/plum/blob/master/app/models/scanned_book.rb#L28) works.

### PR DESCRIPTION
**Pull request by jpstroop**
Will need refinement after the first iteration of plum. Advances pulibrary/plum#1, Closes #6

### CODE REVIEW

**Comment by tampakis** [comment]
Looks good. Just a quick question. Do we care about sorting by creator or title? That would require single-valued fields.

**Comment by terrellt** [comment]
@tampakis I suspect that's something to solve at the application layer

**Comment by jpstroop** [comment]
This is like important for the UI; good point. Probably should add  sort_title property sort_creator properties. @terrellt -- what's the best way to do this? Subproperties of the respective dc properties?

**Comment by jpstroop** [comment]
We could solve creator by sorting by the first one, but it's tougher w/ title because the initial articles would change depending on the language of the record. We easily get this from the record,but it'll be tougher anywhere downstream.

**Comment by terrellt** [comment]
@jpstroop We might want to look into returning literals (with language tags) rather than strings at some point, for this use case. If we want #sort_creator/#sort_title (sounds like we want to centralize the logic for deciding which title/creator to sort on because that logic will be standard between applications) then I'd...I don't know, honestly. First pass would be just add a primary_creator and primary_title attribute I think, and let applications filter those keys out if they're not important?

**Comment by terrellt** [comment]
If you want to store the metadata in triples, then yeah, a DC sub-property would be the way to go, but you'd have to filter out #primary_creator from #creators I'd think. It gets hairy.

**Comment by jpstroop** [comment]
I'm less concerned about creators, but I think we should consider sort_title here, because it's so trivial to get from the MARC data, and much harder anywhere else.

**Comment by terrellt** [comment]
@jpstroop Sounds good.

**Comment by tampakis** [comment]
:+1:

**Pull request merged**
