### PR TITLE
Handing missing box/folder info

### PR DESCRIPTION
**Pull request by escowles**
Switching to a real metadata file and handling missing box/folder info it demonstrates.

### CODE REVIEW

**Comment by jpstroop** [comment]
Do you have a sample component from the PULFA site where this info is missing? I'm wondering if it's related to a change in how Manuscripts handles holding data in their EADs.

**Comment by escowles** [comment]
Yes, these changes were because the records I was working with sometimes has a box number but no folder, or vice versa.  E.g.: http://findingaids.princeton.edu/collections/AC057/c18.xml and http://findingaids.princeton.edu/collections/RBD1/c9626.xml

**Comment by jpstroop** [comment]
Oh, I see. It wasn't missing entirely, just wasn't always box and folder?

http://findingaids.princeton.edu/collections/RBD1/c9626.xml?scope=record

**Comment by escowles** [comment]
Right — the records I was testing with initially all had box and folder — this update was mostly to handle one or the other missing.  For good measure, it also works if both are missing.

**Comment by jpstroop** [comment]
👍

**Pull request merged**
